package com.glassshop.common;

public class Constanst {
	
	public static String REPORT_TEMPLATE_CUSTOMER_ADDRESS = "REPORT_TEMPLATE_CUSTOMER_ADDRESS";
	public static String REPORT_TEMPLATE_CUSTOMER_BACKUP = "REPORT_TEMPLATE_CUSTOMER_BACKUP";
	public static String REPORT_TEMPLATE_ORDER = "REPORT_TEMPLATE_ORDER";
	public static String REPORT_TEMPLATE_REST_ORDER = "REPORT_TEMPLATE_REST_ORDER";
	public static String REPORT_TEMPLATE_SELL = "REPORT_TEMPLATE_SELL";
	
	public static String REPORT_OUTPUT_PATH = "REPORT_OUTPUT_PATH";
	
	public static String REPORT_NAME_CUSTOMER_ADDRESS = "REPORT_NAME_CUSTOMER_ADDRESS";
	public static String REPORT_NAME_CUSTOMER_BACKUP = "REPORT_NAME_CUSTOMER_BACKUP";
	public static String REPORT_NAME_ORDER = "REPORT_NAME_ORDER";
	public static String REPORT_NAME_REST_ORDER = "REPORT_NAME_REST_ORDER";
	public static String REPORT_NAME_SELL = "REPORT_NAME_SELL";

}
